/home/saikrishnalticmu/AndroidStudioProjects/fibonacci/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/HelloComputeNDK/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/MoreTeapots/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/Teapot/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/bitmap-plasma/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/hello-gl2/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/hello-jni/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/hello-neon/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/module-exports/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/native-activity/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/native-audio/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/native-media/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/native-plasma/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/san-angeles/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/test-libstdc++/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/samples/two-libs/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/cpufeatures/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/crazy_linker/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/crazy_linker/tests/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/libportable/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/native_app_glue/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/ndk_helper/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/support/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/android/support/tests/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cpufeatures/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/gabi++/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/gabi++/tests/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/gnu-libstdc++/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/llvm-libc++/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/llvm-libc++/test/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/stlport/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/cxx-stl/system/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/sources/third_party/googletest/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/abcc/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/abcc/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/absolute-src-file-paths/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/ansi/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/awk-trailing-r/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/b8247455-hidden-cxa/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/b9193874-neon/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/build-assembly-file/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/build-mode/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/c++-stl-source-extensions/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/check-armeabi-v7a-prebuilts/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/clang-multiple-arm-enable-ehabi/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/cpp-extensions/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/deprecate-__set_errno/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/fenv/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/flto/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/gnustl-force-all/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/gnustl-force-exceptions/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/gnustl-force-none/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/gnustl-force-rtti/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/graphite-loop/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-install/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-install/path1/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-install/path2/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-static/bar/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-static/foo/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/import-static/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue20862-libpng-O0/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue21132-__ARM_ARCH__/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue22336-ICE-emit-rtl/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue22345-ICE-postreload/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue34613-neon/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue36131-flto-c++11/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue38441-Elf32_auxv_t/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue39824-__BYTE_ORDER/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue39983-PAGE_SIZE/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue40625-SL_IID_ANDROIDBUFFERQUEUESOURCE/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue41297-atomic-64bit/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue41387-uniform-initialized-rvalue/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue41770-_GLIBCXX_HAS_GTHREADS/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue42841-LOCAL_PATH/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue52805-set_new_handler/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue52819-STLPORT_FORCE_REBUILD/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue53163-OpenSLES_AndroidConfiguration/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue53404-backward-compatibility/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue53646-stlport-stl_confix_h/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue53711-un_h/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue54465-invalid-asm-operand-out-of-range/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue54623-dcraw_common-x86-segfault/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue56508-gcc4.7-ICE/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/issue58135-_C_LABEL_STRING/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/lambda-defarg3/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/merge-string-literals/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/mips-fp4/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/multi-abi/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/multi-module-path/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/multi-module-path/path1/foo/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/multi-module-path/path2/bar/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/multiple-static-const/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/ndk-build-unit-tests/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/ndk-out/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/no-installable-modules/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/prebuild-stlport/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/prebuilt-copy/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/prebuilt-copy/prebuilts/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/project-properties/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/pthread-rwlock-initializer/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/ssax-instructions/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/stdint-c++/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/stlport-src-suffix/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/stlport-static-assert/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/system-cpp-headers/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/target-c-includes/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/test-c-only-flags/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/test-gnustl-chrono/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/test-inet-defs/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/test-stlport_static-exception-force-rebuild/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/thin-archives/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/topological-sort/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-bad-modules/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-no-ldflags-in-static-libraries/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-no-ldlibs-in-static-libraries/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-no-modules/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-noabi/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-non-system-libs-in-linker-flags/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/warn-thin-archive-is-for-static-libraries/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/build/wchar_t-size/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/b8708181-Vector4/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/bitfield/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/clone/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/crazy_linker/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/emm/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/exceptions-crash/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/fenv/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/gnustl-shared-1/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/hard-float/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue19851-sigsetjmp/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue20176-__gnu_Unwind_Find_exidx/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue22165-typeinfo/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue28598-linker-global-ref/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue35933-lambda/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue38121/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue39680-chrono-resolution/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue42891-boost-1_52/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue46718-iostream-crash-gnustl/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/issue46718-iostream-crash-stlport/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/multi-static-instances/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/stat/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/static-executable/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-android-support/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-basic-exceptions/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-basic-rtti/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-compiler-bug-1/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-cpufeatures/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-cxx-init-array/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gabi++/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl-1/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl-2/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl-copy_vector_into_a_set/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl-full/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl_shared-exception/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-gnustl_static-exception/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-googletest-full/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-googletest-gnustl/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-googletest-stlport/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-libc++/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-openmp/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-stlport/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-stlport-copy_vector_into_a_set/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-stlport-rtti/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-stlport_shared-exception/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-stlport_static-exception/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-unwind-struct/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/test-wait/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/device/whole-static-libs/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/rs/cppallocation/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/rs/cppbasic/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/rs/cppstrided/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/rs/latency/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/tests/rs/typecheck/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-BuildEnv/android-ndk/toolchains/renderscript/prebuilt/linux-x86/lib/clang/3.3/include/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-TTS-Engine-for-Android/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_RoboTutor/Flite-XPrize/app/src/main/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/NDKTest/jni/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/android/cpufeatures/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/android/native_app_glue/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/android/ndk_helper/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/android/support/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/android/support/tests/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/gabi++/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/gabi++/tests/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/llvm-libc++/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/llvm-libc++/test/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/llvm-libc++abi/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/stlport/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/cxx-stl/system/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/googletest/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/shaderc/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/shaderc/libshaderc/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/shaderc/libshaderc_util/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/shaderc/third_party/Android.mk
/home/saikrishnalticmu/Documents/Project_sirisha19sept2016/android-ndk-r12b/sources/third_party/vulkan/src/build-android/jni/Android.mk
/home/saikrishnalticmu/hacks/repos/Flite-TTS-Engine-for-Android/jni/Android.mk
/home/saikrishnalticmu/hacks/repos/GF/src/ui/android/jni/Android.mk
/home/saikrishnalticmu/hacks/repos/Hear2Read_TTS_Tamil_Engine_Android/jni/Android.mk
/home/saikrishnalticmu/tools/Festival/Bard/flite-1.9.0-current/android/app_code/jni/Android.mk
/home/saikrishnalticmu/tools/SDL/Android.mk
/home/saikrishnalticmu/tools/SDL/android-project/jni/Android.mk
/home/saikrishnalticmu/tools/SDL/android-project/jni/src/Android.mk
/home/saikrishnalticmu/tools/SDL2-2.0.4/Android.mk
/home/saikrishnalticmu/tools/SDL2-2.0.4/android-project/jni/Android.mk
/home/saikrishnalticmu/tools/SDL2-2.0.4/android-project/jni/src/Android.mk
/home/saikrishnalticmu/tools/SDL2_ttf-2.0.14/Android.mk
/home/saikrishnalticmu/tools/SDL_ttf-2.0.11/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/HelloComputeNDK/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/MoreTeapots/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/Teapot/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/bitmap-plasma/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/hello-gl2/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/hello-jni/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/hello-neon/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/module-exports/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/native-activity/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/native-audio/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/native-media/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/native-plasma/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/san-angeles/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/test-libstdc++/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/samples/two-libs/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/cpufeatures/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/crazy_linker/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/crazy_linker/tests/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/libportable/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/native_app_glue/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/ndk_helper/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/support/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/android/support/tests/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cpufeatures/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/gabi++/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/gabi++/tests/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/gnu-libstdc++/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/llvm-libc++/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/llvm-libc++/test/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/stlport/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/cxx-stl/system/Android.mk
/home/saikrishnalticmu/tools/android-ndk/sources/third_party/googletest/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/abcc/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/abcc/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/absolute-src-file-paths/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/ansi/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/awk-trailing-r/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/b8247455-hidden-cxa/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/b9193874-neon/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/build-assembly-file/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/build-mode/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/c++-stl-source-extensions/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/check-armeabi-v7a-prebuilts/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/clang-multiple-arm-enable-ehabi/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/cpp-extensions/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/deprecate-__set_errno/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/fenv/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/flto/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/gnustl-force-all/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/gnustl-force-exceptions/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/gnustl-force-none/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/gnustl-force-rtti/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/graphite-loop/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-install/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-install/path1/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-install/path2/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-static/bar/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-static/foo/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/import-static/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue20862-libpng-O0/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue21132-__ARM_ARCH__/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue22336-ICE-emit-rtl/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue22345-ICE-postreload/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue34613-neon/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue36131-flto-c++11/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue38441-Elf32_auxv_t/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue39824-__BYTE_ORDER/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue39983-PAGE_SIZE/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue40625-SL_IID_ANDROIDBUFFERQUEUESOURCE/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue41297-atomic-64bit/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue41387-uniform-initialized-rvalue/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue41770-_GLIBCXX_HAS_GTHREADS/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue42841-LOCAL_PATH/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue52805-set_new_handler/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue52819-STLPORT_FORCE_REBUILD/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue53163-OpenSLES_AndroidConfiguration/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue53404-backward-compatibility/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue53646-stlport-stl_confix_h/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue53711-un_h/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue54465-invalid-asm-operand-out-of-range/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue54623-dcraw_common-x86-segfault/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue56508-gcc4.7-ICE/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/issue58135-_C_LABEL_STRING/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/lambda-defarg3/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/merge-string-literals/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/mips-fp4/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/multi-abi/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/multi-module-path/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/multi-module-path/path1/foo/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/multi-module-path/path2/bar/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/multiple-static-const/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/ndk-build-unit-tests/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/ndk-out/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/no-installable-modules/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/prebuild-stlport/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/prebuilt-copy/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/prebuilt-copy/prebuilts/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/project-properties/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/pthread-rwlock-initializer/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/ssax-instructions/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/stdint-c++/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/stlport-src-suffix/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/stlport-static-assert/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/system-cpp-headers/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/target-c-includes/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/test-c-only-flags/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/test-gnustl-chrono/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/test-inet-defs/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/test-stlport_static-exception-force-rebuild/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/thin-archives/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/topological-sort/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-bad-modules/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-no-ldflags-in-static-libraries/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-no-ldlibs-in-static-libraries/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-no-modules/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-noabi/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-non-system-libs-in-linker-flags/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/warn-thin-archive-is-for-static-libraries/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/build/wchar_t-size/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/b8708181-Vector4/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/bitfield/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/clone/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/crazy_linker/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/emm/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/exceptions-crash/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/fenv/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/gnustl-shared-1/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/hard-float/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue19851-sigsetjmp/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue20176-__gnu_Unwind_Find_exidx/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue22165-typeinfo/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue28598-linker-global-ref/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue35933-lambda/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue38121/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue39680-chrono-resolution/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue42891-boost-1_52/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue46718-iostream-crash-gnustl/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/issue46718-iostream-crash-stlport/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/multi-static-instances/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/stat/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/static-executable/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-android-support/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-basic-exceptions/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-basic-rtti/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-compiler-bug-1/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-cpufeatures/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-cxx-init-array/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gabi++/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl-1/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl-2/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl-copy_vector_into_a_set/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl-full/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl_shared-exception/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-gnustl_static-exception/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-googletest-full/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-googletest-gnustl/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-googletest-stlport/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-libc++/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-openmp/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-stlport/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-stlport-copy_vector_into_a_set/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-stlport-rtti/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-stlport_shared-exception/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-stlport_static-exception/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-unwind-struct/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/test-wait/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/device/whole-static-libs/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/rs/cppallocation/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/rs/cppbasic/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/rs/cppstrided/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/rs/latency/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/tests/rs/typecheck/jni/Android.mk
/home/saikrishnalticmu/tools/android-ndk/toolchains/renderscript/prebuilt/linux-x86/lib/clang/3.3/include/Android.mk
